SAP/ai-sdk-js

package.json

Adjust the script so `pnpm compile` when run separately also runs compile recursively

chore: Adjust compile script

---

.github/dependabot.yml

Group dependency updates to make sure, that all SDK dependencies are always updated together.

chore: Group SAP Cloud SDK dependency updates

---

.github/workflows/publish-canary.yml

This should fix the nightly canary release.
@jjtang1985 should we add the check, whether anything was changed since the last release now or later?

chore: Fix nightly canary release

---

packages/ai-core/package.json
packages/ai-core/src/tests/artifact-api.test.ts
packages/ai-core/src/tests/configuration-api.test.ts
packages/ai-core/src/tests/deployment-api.test.ts
packages/ai-core/src/tests/execution-api.test.ts
packages/ai-core/src/tests/scenario-api.test.ts
packages/gen-ai-hub/package.json

While re-generating our clients, we noticed that deprecated files are not automatically removed, existing ones are only overwritten.
As we want to get rid of any manual steps during and after generation, we need to clear the output directory in the future.
With this PR, we switch from overwriting to clearing the output directory.
To keep our tests, they are moved to a separate testing directory.

chore: Refactor client test structure and generation script

---

.changeset/config.json
.github/workflows/publish-canary.yml

This removes some of the config that I added previously:
1. Keep only one package in the dummy changelog for canary - due to the fixed versioning this is enough.
2. Do not ignore packages - all packages that should not be released have the private flag and this prevents them from being published.
This means for as long as we keep fixed versioning there is not need to adjust the config when changing the package structure.

chore: Simplify canary release config

---

packages/gen-ai-hub/src/index.ts

This function is supposed to be used publicly, which needs to be added to the index file

fix: Missing visibility of azureContentFilter

---

packages/gen-ai-hub/src/orchestration/orchestration-client.test.ts
packages/gen-ai-hub/src/orchestration/orchestration-completion-post-request.test.ts
tests/e2e-tests/src/orchestration.test.ts

Adjusts tests as part of AI/gen-ai-hub-sdk-js-backlog#44
The way we define placeholders for parameters in the template changed, see [here](https://github.tools.sap/AI/llm-orchestration/blob/main/src/spec/api.yaml#L278), this PR adjusts tests accordingly.
I also enhanced the Orchestration E2E test, just in case, to be aware if something changes, but this can be discussed.
Before:
```TypeScript
template: [ { role: 'user', content: 'Create {number} paraphrases of {phrase}' } ]
```
After:
```TypeScript
template: [ { role: 'user', content: 'Create {{?number}} paraphrases of {{?phrase}}' } ]
```

chore: Adjust orchestration tests

---

.github/workflows/build.yml

As in the title, the build job is unnecessary and executed multiple times.

chore: Remove unnecessary build job

---

packages/core/src/http-client.ts
packages/gen-ai-hub/src/client/openai/openai-client.test.ts
packages/gen-ai-hub/src/client/openai/openai-client.ts
packages/gen-ai-hub/src/orchestration/orchestration-client.ts
packages/gen-ai-hub/src/utils/deployment-resolver.test.ts
packages/gen-ai-hub/src/utils/deployment-resolver.ts
sample-code/src/aiservice.ts
tests/type-tests/test/openai.test-d.ts

AI/gen-ai-hub-sdk-js-backlog#92.
This combines the deployment ID and model into one parameter. I also refactored some of the code to be more concise and fixed some issues that I found along the way.
Unfortunately the API does not get better for orchestration. Regardless, I would like to merge this one before adjusting it in here and getting inspired from python.

feat: Combine deployment resolution and model

---

packages/core/internal.d.ts
packages/core/internal.js
packages/gen-ai-hub/internal.js

I noticed the files were exporting CJS instead of ESM. Somehow this causes issues in ai-core where I wanted to add this, but not in the other packages ¯\\\_(ツ)\_/¯

fix: Internal files should also be ESM

---

scripts/check-public-api.ts

Updating the script to ignore AI_CORE_CLIENTS during the checking process because by default, everything in there should be public. 
This is just a temporary workaround to merge https://github.com/SAP/ai-sdk-js/pull/107. We would ideally split the script to handle external imports and internal imports separately in the future.

fix: Update public api script

---

packages/core/src/http-client.ts
tests/type-tests/test/http-client.test-d.ts

AI/gen-ai-hub-sdk-js-backlog#106.
Remove `method` property from `CustomRequestConfig` as user should not define it. Currently, it is even mandatory to define this property.

fix: Remove method property

---

.github/workflows/smoke-tests.yml

AI/gen-ai-hub-sdk-js-backlog#107.
With this PR we fix the smoke tests, or rather run them after we released a new canary version.
Canary versions are released everyday at 1 AM, now our smoke tests run at 2 AM.

chore: Change nightly test schedule

---

pnpm-lock.yaml
tests/smoke-tests/package.json

AI/gen-ai-hub-sdk-js-backlog#80.
Use canary versions for ai sdk packages in smoke tests.

revert: Use canary versions for smoke tests dependencies

---

packages/ai-api/src/tests/deployment-api.test.ts
packages/core/src/http-client.ts
packages/core/src/openapi-request-builder.ts

The ai-api clients use the OpenAPI req builders which uses `HttpRequestConfigWithOrigin`. The `executeRequest` and `mergeWithDefaultRequestConfig` on the other hand expect `HttpRequestConfig` which causes incorrect/incomplete headers and params to be sent.

fix: Merge request config headers and params

---

packages/ai-api/src/index.ts
packages/ai-api/src/utils/deployment-resolver.ts
packages/core/src/http-client.test.ts
packages/core/src/http-client.ts
packages/core/src/index.ts
packages/orchestration/src/index.ts
packages/orchestration/src/orchestration-client.test.ts
packages/orchestration/src/orchestration-client.ts
packages/orchestration/src/orchestration-completion-post-request.test.ts
packages/orchestration/src/orchestration-filter-utility.test.ts
packages/orchestration/src/orchestration-types.ts
sample-code/src/orchestration.ts
tests/e2e-tests/src/orchestration.test.ts
tests/type-tests/test/http-client.test-d.ts
tests/type-tests/test/orchestration.test-d.ts

AI/gen-ai-hub-sdk-js-backlog#104.
I renamed a few types and properties and removed a few types that I noticed were unused.
I added one TODO because we export some types directly, however those types do not comply with our style guide and therefore have inconsistent naming.

chore: Make API more consistent

---

.gitignore
packages/foundation-models/package.json

`sed` commands are weird on mac. This should solve it with a gitignore workaround

chore: Fix sed for bash BSD

---

packages/orchestration/src/index.ts

Grounding types are still subject to change and not released yet

chore: remove grounding types from indext.ts

---

packages/orchestration/src/index.ts

Reverts SAP/ai-sdk-js#146
The original PR build was not successful.

revert: "chore: remove grounding types from indext.ts"

---

.github/dependabot.yml

Currently dependabot only updates npm dependencies, but not github actions. This should fix that.

chore: Update github actions as well

---

.changeset/famous-needles-act.md
package.json
packages/foundation-models/src/azure-openai/azure-openai-chat-completion-response.test.ts
packages/foundation-models/src/azure-openai/azure-openai-embedding-response.test.ts
packages/foundation-models/src/azure-openai/azure-openai-embedding-response.ts
packages/orchestration/src/orchestration-response.test.ts

AI/gen-ai-hub-sdk-js-backlog#143.
Add more test. I also noticed a bug in the convenience method in embedding response class.

chore: Add openai response tests

---

packages/foundation-models/README.md
packages/orchestration/README.md

AI/gen-ai-hub-sdk-js-backlog#139.
Add documentation for
- setting `model_version` in orchestration
- the used Azure OpenAI API version
- setting `requestConfig` in
- Azure OpenAI client
- orchestration client

chore: Docs add model version and api version

---

.changeset/two-bottles-juggle.md
packages/ai-api/src/utils/deployment-resolver.ts
packages/core/src/http-client.test.ts
packages/core/src/http-client.ts
packages/foundation-models/src/azure-openai/azure-openai-chat-client.test.ts
packages/foundation-models/src/azure-openai/azure-openai-chat-client.ts
packages/foundation-models/src/azure-openai/azure-openai-embedding-client.ts
packages/langchain/src/openai/chat.ts
packages/langchain/src/openai/embedding.ts
packages/orchestration/src/orchestration-client.test.ts
packages/orchestration/src/orchestration-client.ts
test-util/mock-http.ts

AI/gen-ai-hub-sdk-js-backlog#146.
A user discovered a bug where we do not properly set the resource group after they have set it in the client's initialization.
With this fix, this should be fixed.

chore: Fix resource group header

---

packages/ai-api/README.md

Updated broken link on the api-ai `README.md`.
I assumed the proper link was the same as in the corresponding link used in the other packages.
- N/A - Code is tested (Unit, E2E)
- N/A - Error handling created / updated & covered by the tests above
- N/A - (Optional) Aligned changes with the Java SDK
- N/A - (Optional) Release notes updated

docs: Fixed broken link on api-ai README

---

README.md

This commits added the standard `README.md` section _Requirements and Setup_ and refers to the documentation of the individual packages.
It also adds a link to the documentation of the SAP AI Core service on the first paragraph.
Please provide a description of what your change does and why it is needed.
- N/A - Code is tested (Unit, E2E)
- N/A - Error handling created / updated & covered by the tests above
- N/A - (Optional) Aligned changes with the Java SDK
- N/A - (Optional) Release notes updated

docs: Minor README improvement

---

packages/foundation-models/README.md

The Azure keyword is missing in the OpenAI client documentation.

chore: Add azure keyword for OpenAI client

---

tests/smoke-tests/test/smoke.test.ts

Fixes failing smoke test run, wrong API endpoint used for testing, `/ai-api/get-deployments` instead of `/ai-api/deployments`
- ~[ ] Documentation updated~

fix: Wrong endpoint in smoke test

---

tests/e2e-tests/src/open-ai-langchain.test.ts

The RAG langchain test is currently flaky due to the string we test for not always being part of the response.
As the prompt clearly asks for "code examples", at least the instantiation of the class being part of the response is a reasonable assumption, therefore we now test for the response to include the class name of the orchestration client.

chore: Update RAG langchain test

---

sample-code/src/orchestration.ts

Our output filter tests sometimes do not work as intended, as the LLM refuses to create content that would hit the filter.
With the new prompt, the LLM should reliably create the intended output, which will then hit the output filter.
Orchestration colleagues use the [same prompt](https://github.tools.sap/AI/llm-orchestration/blob/7fac544359cf60ce61093b46acbf67ee17a7cc40/tests_integration/test_orchestration_streaming.py#L412) to test their output filtering.

chore: Make outputfilter test less flaky

---

sample-code/src/foundation-models/azure-openai.ts

~AI/gen-ai-hub-sdk-js-backlog#ISSUENUMBER.~
E2E was failing due to a prompt, which causes a large amount of token consumption.
- ~[ ] Documentation updated~

fix: E2E due to large token consumption

---

scripts/check-public-api.ts

The public api check started failing for ai-api (now because we added `Node16` option in this [PR](https://github.com/SAP/cloud-sdk-js/pull/5184)), before it defaulted to `module: commonjs`, which means `moduleResolution: node`. This settings does not give compilation errors when esm is used with require syntax).
It fails because program.emit() still transpiles to commonjs but because `moduleResolution` is `node16`, it gives compile-time errors. `emit()` function was not able to infer that the sourceFile is esm because it didn't find a package.json file and therefore didnt find `type: module` setting. 
@shibeshduw This should be fixed in the github action as well (in the cloud sdk)

chore: Fix public api check

---

.github/workflows/build.yml

The public API check ignores checking the generated client as it currently ignores paths matching `.*?/client/[^/]+/schema`
For the RAGe client, we had to introduce a nested folder structure.
Hence, updating the regex for public API check, to also ignore nested folder structures in the generated client.
- ~[ ] Documentation updated~

chore: Ignore nested folders in generated client in public API check

---

packages/orchestration/README.md

SAP/ai-sdk-js-backlog#180.
Tiny fix to remove `help.sap.com` in documentation.

fix: Remove help.sap.com in orchestration doc

---

pnpm-lock.yaml
sample-cap/README.md
sample-cap/package.json

The bump causes the pipeline to fail as the ai-sdk dependencies in sample-cap are also updated but the pnpm-lock isn't. This results in conflicts and breaks the pipeline.
For running locally (or in workflow without cf deployment), using the pnpm `workspace:^ ` protocol should be fine. Building the app locally is also sufficient for testing transpilation. For deployment, the users can update the dependency as documented. (The sample-cap is currently not used in any tests, workflows (should be fixed)).
**Alternative:** 
Another solution could be that sample-cap is not considered a workspace package, so changeset will not try to bump anything. But this has the disadvantage that you always have to cd to the dir to execute commands. Though not a huge deal for now.

chore: Fix sample-cap dependencies

---

pnpm-lock.yaml
tests/smoke-tests/package.json

~SAP/ai-sdk-js-backlog#ISSUENUMBER.~
Smoke tests package was missing `@sap-ai-sdk/document-grounding` dependency.

fix: Smoke tests missing dependency

---

.github/workflows/e2e-tests.yaml
tests/e2e-tests/README.md
tests/e2e-tests/src/deployment-api.test.ts

SAP/ai-sdk-js-backlog#211.
This PR aligns the e2e tests with the [Java sdk](https://github.com/SAP/ai-sdk-java/blob/fcab936bb6b9c068d27d0ddf6d15feb3dad2cf2a/sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/DeploymentTest.java#L14). Essentially we ignore the modify endpoint and just delete a newly created deployment. 
Test run: https://github.com/SAP/ai-sdk-js/actions/runs/12691689015
I have also removed cleanup deployments from GH Actions but left the script as it is because it is still useful as a utility imo.

fix: Deployment-api e2e-tests

---

packages/orchestration/src/model-types.ts

SAP/ai-sdk-js-backlog#202.
Remove exclusion of gpt-4o-mini for orchestration.

chore: Include gpt-4o-mini for orchestration

---

.changeset/sharp-pianos-press.md

Updates changelog to include info that `model_params` is optional

chore: Update sharp-pianos-press.md

---

packages/foundation-models/README.md

Closes SAP/ai-sdk-js-backlog#166.
Adds documentation to replace API version in Azure OpenAI Client

chore: Add documentation to replace API version in Azure OpenAI Client

---

packages/orchestration/README.md

- Added streaming to table of contents
- Moved streaming to a bit below, as it's more advanced API. Also, it needs the context like templating, Json config etc.

chore: Update table of contents for orchestration doc

---

.github/actions/setup/action.yml
pnpm-lock.yaml

Since the latest version of pnpm, our checksums start failing if an outdated pnpm version is used, with this PR, we upgrade to the latest version.

chore: Update pnpm to version 10 in setup github action

---

.github/workflows/spec-update.yaml

If we use the normal token, the created PRs will not trigger CI/CD runs

fix: Spec Update Workflow Permissions

---

packages/orchestration/README.md
sample-code/src/index.ts
sample-code/src/orchestration.ts
sample-code/src/server.ts
tests/e2e-tests/src/orchestration.test.ts

Closes SAP/ai-sdk-js-backlog#219.

feat: Orchestration with Prompt Registry

---

packages/orchestration/README.md
sample-code/src/orchestration.ts

Closes SAP/ai-sdk-js-backlog#224.
Adds documentation indicating that `image_url` content type can only be used in `user` messages.

chore: Document limitation of `image_url` content type in Orchestration

---

.github/workflows/dependabot-pnpm-lock.yml

Adds a new workflow to update the `pnpm-lock.yaml` on dependabot PRs
Dependabot PRs are not created with `pnpm v10`, hence we need an additional action to update the lock files generated with version 10 explicitly.

chore: Add new workflow for updating dependabot PRs

---

.changeset/purple-lizards-buy.md
packages/ai-api/src/utils/deployment-resolver.ts
packages/foundation-models/src/azure-openai/azure-openai-chat-client.ts
packages/foundation-models/src/azure-openai/azure-openai-embedding-client.ts
packages/orchestration/src/orchestration-client.ts

We ignored destinations in our deployment id lookup and only included it in the requests we execute.
With this PR, we also do the look-up flow based on the destination (if any was provided).
Relates to #547

fix: Include destinations in deployment id lookup

---

.github/ISSUE_TEMPLATE/bug_report.yml

Closes SAP/ai-sdk-js-backlog#210.
Adds a region field to the bug report template. The list of options were taken from:
- https://me.sap.com/notes/3485650 (Internally available resources)
- https://me.sap.com/notes/3437766 (Externally available resources)

chore: Add region to bug report template

---

tests/e2e-tests/src/orchestration.test.ts

Fixes a typo in an e2e test that causes it to fail -> https://github.com/SAP/ai-sdk-js/actions/runs/13445525274/job/37569879740

fix: E2E test typo

---

.changeset/hip-tools-smile.md
packages/orchestration/README.md
packages/orchestration/src/index.ts
packages/orchestration/src/orchestration-client.test.ts
packages/orchestration/src/orchestration-types.ts
packages/orchestration/src/util/filtering.test.ts
packages/orchestration/src/util/filtering.ts
sample-code/src/orchestration.ts
test-util/data/orchestration/orchestration-chat-completion-multiple-filter-config.json
tests/type-tests/test/orchestration.test-d.ts

Closes SAP/ai-sdk-js-backlog#205.
This PR adds a convenience function to enable filter categories for Llama guard filter.
The built filter can then be used in the filtering configuration of the Orchestration client.

feat: Add convenience function for LlamaGuard Filter

---

.changeset/shy-socks-shake.md
packages/core/src/model-types.ts

Closes SAP/ai-sdk-js-backlog#244.
Add `o1`, `o3-mini` and `alephalpha-pharia-1-7b-control` to the available model list.

chore: Update model list

---

sample-code/package.json
tests/smoke-tests/package.json

I dont remember why we pinned the node engine to 20. But I keep getting warnings when using node 22 (which is what we officially support) that I'm using an incompatible version. I ran both [smoke](https://github.com/SAP/ai-sdk-js/actions/runs/13768082407) and [e2e test](https://github.com/SAP/ai-sdk-js/actions/runs/13768248283) on this branch and they both succeed. So I believe its fine to remove the engine.

chore: Remove node engine 20 in sample app

---

.github/workflows/spec-update.yaml

feat: Support document grounding and prompt registry spec update

---

.changeset/deep-ends-attend.md
README.md
packages/prompt-registry/README.md
sample-code/README.md
sample-code/src/index.ts
sample-code/src/server.ts
tests/e2e-tests/src/prompt-registry.test.ts

Relates to SAP/ai-sdk-js-backlog#223.
- Add changeset
- Add missing error handling section in README.md
- Add e2e
- Update `sample-code`

feat: Prompt registry follow up

---

.changeset/dry-carpets-find.md
packages/orchestration/README.md
packages/orchestration/src/index.ts
packages/orchestration/src/orchestration-types.ts
packages/orchestration/src/util/index.ts
packages/orchestration/src/util/masking.test.ts
packages/orchestration/src/util/masking.ts
sample-code/src/orchestration.ts
tests/type-tests/test/orchestration.test-d.ts

Closes SAP/ai-sdk-js-backlog#231.
Add convenience function `buildDpiMaskingProvider()`.

feat: Add convenience for masking

---

.changeset/dark-flies-try.md
README.md
packages/core/src/model-types.ts
packages/document-grounding/README.md
packages/document-grounding/src/tests/vector-api.test.ts
packages/foundation-models/README.md
packages/langchain/src/openai/README.md
sample-code/src/document-grounding.ts
sample-code/src/foundation-models/azure-openai.ts
sample-code/src/langchain-azure-openai.ts
tests/type-tests/test/azure-openai.test-d.ts

Closes SAP/ai-sdk-js-backlog#257.
Replaces `text-embedding-ada-002` in our sample-code and documentation with the suggested replacements according to [SAP notes](https://me.sap.com/notes/3437766).

chore: Remove deprecated models

---

.github/workflows/smoke-tests.yml

Relates to SAP/ai-sdk-js-backlog#221.
https://github.com/vchrisb/setup-cf/commit/7e7a19573c9a2cf138f00399472dfc4e423d1f92
Pin the version to `7e7a19573c9a2cf138f00399472dfc4e423d1f92` (release version v1.0.3).

chore: Pin `vchrisb/setup-cf` version using full SHA

---

.changeset/fast-showers-prove.md
packages/orchestration/README.md
packages/orchestration/src/orchestration-types.ts
packages/orchestration/src/util/grounding.test.ts
packages/orchestration/src/util/grounding.ts
sample-code/src/document-grounding.ts
sample-code/src/orchestration.ts
sample-code/src/server.ts

Closes SAP/ai-sdk-js-backlog#267.
`buildDocumentGroundingConfig()` now support `metadata_params` as an optional parameter. When defining this property, the grounding result will include metadata as part of the JSON string.
Sample result for grounding module:
```json
{
"message": "grounding result",
"data": {
"grounding_query": "grounding call",
"grounding_result": "[{\"content\": \"The last SAP AI SDK JavaScript end to end test was run at 1743431349413.\", \"metadata\": {\"context\": [\"sap-ai-sdk-js\"]}}]"
}
}
```
Since `metadata` is now part of the `grounding_result` it can be used / mentioned in the prompt.

feat: Support setting `metadata_params` property in `buildDocumentGroundingConfig()` convenience function

---

sample-code/src/orchestration.ts

`templating` was not typed. Will cause issue later when migrating to a new orchestration spec.

chore: Add type for `templating` in sample code

---

.changeset/big-breads-show.md
packages/foundation-models/src/azure-openai/azure-openai-chat-completion-stream.test.ts
packages/foundation-models/src/azure-openai/azure-openai-chat-completion-stream.ts

A bug reported [here](https://github.com/SAP/ai-sdk-js/issues/670). `finishReason` is nullable.

fix: OpenAI streaming if finish reason is null

---

.github/workflows/spec-update.yaml

Closes SAP/ai-sdk-js-backlog#305.
The spec update creates spec/update/... branches. However, we never delete them if no PR is needed. Then the next time, we checkout those branches from remote origin, which is probably behind of main. This causes issue like in http://github.com/SAP/ai-sdk-js/pull/693
In this PR we rebase the current main when checking out the existing branch. In principal, there should be no rebase conflicts as developers should not change the generated files or making diverged changes to the spec file. And no one should ever check out a spec branch and push changes manually, so no need to force push.

fix: Delete existing origin branch when running spec update workflow

---

scripts/add-changelog.ts

We don't have `[Core Modules]` in the ai-sdk release notes, different from cloud sdk. Thus, removing it.

chore: Update add-changelog.ts

---

tests/e2e-tests/src/document-grounding.test.ts

Closes SAP/ai-sdk-js-backlog#286.
With this PR, we add a test to retrieve S3 information with document grounding.

chore: Support s3 document grounding service.

---

.changeset/dark-geese-laugh.md

Adds a changeset for the support of S3-based document grounding.

chore: Add changeset

---

packages/langchain/src/orchestration/client.ts
packages/langchain/src/orchestration/util.ts
packages/orchestration/src/orchestration-types.ts
packages/orchestration/src/util/module-config.ts
tests/type-tests/test/orchestration.test-d.ts

This PR fixes some issues identified in the failing e2e test:
- Tightened types of `TemplatingModuleConfig` to `Xor<Template, Template_Ref>` so user gets an error when they set both `template` and `template_ref`
- Not doing a shallow copy of the instance property config when concatenating `messages`
- Improving the TypeGuard to check for `template_ref`

chore: Fix types and checks for TemplatingModuleConfig

---

packages/foundation-models/src/azure-openai/azure-openai-chat-completion-stream-response.ts
packages/foundation-models/src/azure-openai/azure-openai-chat-completion-stream.ts
packages/orchestration/src/orchestration-stream-response.ts
packages/orchestration/src/orchestration-stream.ts

Closes SAP/ai-sdk-js-backlog#352.
With this PR, I move the post-processing into the stream, this way the tool calls are only computed once, and issues with any of them are visible immediately instead of after calling the respective function.
Relates to:
- #840

chore: Add postprocessing to tool calls

---

packages/orchestration/src/orchestration-response.ts
packages/orchestration/src/orchestration-stream-chunk-response.ts

Closes SAP/ai-sdk-js-backlog#306.
The bug listed on the ticket was resolved by Orchestration in 2506b update. 
Since `role` is now a required field in the response message, `getChoices()` can be safely typed as `LLMChoice[]`.

chore: Use correct type cast in `findChoiceByIndex()`

---

.changeset/cuddly-areas-deny.md
packages/langchain/src/openai/util.test.ts
packages/langchain/src/openai/util.ts
packages/langchain/src/orchestration/__snapshots__/util.test.ts.snap
packages/langchain/src/orchestration/util.test.ts
packages/langchain/src/orchestration/util.ts
test-util/tools.ts

Closes SAP/ai-sdk-js-backlog#371.
User issue: SAP/ai-sdk-js#870
Use `isInteropZodSchema` instead of `isZodSchemaV4` to support both Zod v3 and v4 schema input from user.

fix: Zod schema validation for both v3 and v4

---

sample-code/src/langchain-azure-openai.ts

E2E was failing https://github.com/SAP/ai-sdk-js/actions/runs/16482805208
Returning object instead of JSON string to make it work.

fix: E2E with structured output

---

tests/e2e-tests/src/orchestration.test.ts

e2e was failing due to passing the old controller to signal param.

fix: E2E stream signal param

---

.github/actions/setup/action.yml
.github/workflows/auto-fix-lint.yml
.github/workflows/build.yml
.github/workflows/bump.yml
.github/workflows/dependabot-pnpm-lock.yml
.github/workflows/draft-release.yml
.github/workflows/e2e-tests.yaml
.github/workflows/publish-canary.yml
.github/workflows/publish.yml
.github/workflows/smoke-tests.yml

[Reusable flow `setup` fails](https://github.com/SAP/ai-sdk-js/actions/runs/17546129492/job/49827913432) due to using `vars` in input's `default` property.
Fix by reading `vars` in individual workflow and provide the value over `node-version` input property to the reusable workflow.

fix: Read `vars` from input instead of `default`

---

.github/workflows/publish-canary.yml

Disabling canary release job until v2 releases.

chore: Disable canary release job until v2 release

---

.changeset/empty-wasps-lick.md
packages/orchestration/src/util/filtering.ts
styles/config/vocabularies/SAP/accept.txt

Unfortunately, the JSDoc of this function was overlooked and was not changed to the correct usage.

fix: JSDoc example of `buildAzureContentSafetyFilter()` function

---

sample-code/src/langchain-orchestration.ts
sample-code/src/server.ts
sample-code/src/tutorials/mcp/weather-mcp-server.ts

Relates to SAP/ai-sdk-js#1145.
Relates to SAP/ai-sdk-js-backlog#374
The first part is about switching from using `zod/v4` to `zod/v3` with `zod@3.x` package in `sample-code/src/tutorials/mcp/weather-mcp-server.ts` since `@modelcontextprotocol/sdk` does not even support `zod/v4` from `zod@3.x` due to the outdated zod dependency.
`modelcontextprotocol` typescript sdk is working on supporting `zod@4.x` package directly. See https://github.com/modelcontextprotocol/typescript-sdk/pull/869.
The second part is to add a new sample-code show-casing how to use LangChain's MCP adapter with pure LangChain `bindTools()` without LangGraph. (as requested in SAP/ai-sdk-js#1145).

chore: Use `zod/v3` in Agent tutorial and add plain LangChain MCP sample code
