- packages/gen-ai-hub/src/client/openai/openai-client.ts
- packages/gen-ai-hub/src/index.ts
- packages/gen-ai-hub/src/orchestration/api/schema/completion-post-request.ts
- packages/gen-ai-hub/src/orchestration/index.ts
- packages/gen-ai-hub/src/orchestration/orchestration-client.test.ts
- packages/gen-ai-hub/src/orchestration/orchestration-client.ts
- packages/gen-ai-hub/src/orchestration/orchestration-types.ts
- type-tests/orchestration.test-d.ts
Before:
```TypeScript
client.chatCompletion({
deploymentConfiguration: { deploymentId: 'id' },
messages_history: [{ role: 'system', content: 'Test system message' }],
orchestration_config: {
module_configurations: {
templating_module_config: {
template: [{ role: 'user', content: 'Hello!' }]
},
llm_module_config: {
model_name: 'gpt-35-turbo-16k',
model_params: {
max_tokens: 50,
temperature: 0.1
}
}
}
}
}
```
After:
```TypeScript
client.chatCompletion({
deploymentConfiguration: { deploymentId: 'id' },
llmConfig: {
model_name: 'gpt-35-turbo-16k',
model_params: { max_tokens: 50, temperature: 0.1 }
},
prompt: {
template: [{ role: 'user', content: 'Hello!' }],
messages_history: [{ role: 'system', content: 'Test system message' }]
}
})
);
```
> feat: Simplify orchestration api parameters

- pnpm-lock.yaml
lock file seems to be broken, not sure how this passed the PR checks.
> chore: Fix pnpm-lock

- .github/codeql/codeql-config.yml
- .github/workflows/codeql.yml
I switched the CodeQL setup to the advanced setup, so that we can only scan the prodcutive code.
> chore: Add codeql config

- package.json
- packages/ai-core/package.json
- packages/gen-ai-hub/package.json
- pnpm-lock.yaml
Move dependencies from root package to respective packages. Also remove dependencies not required.
> chore: Remove unwanted dependencies

- .github/workflows/e2e-test.yaml
- global-test-setup.ts
- global-test-teardown.ts
- packages/core/src/context.test.ts
- packages/core/src/context.ts
- sample-code/README.md
- test-util/mock-http.ts
Environment variables should be uppercase.
> chore: Change service key env var to `AICORE_SERVICE_KEY`

- packages/core/src/http-client.ts
- tests/type-tests/test/http-client.test-d.ts
AI/gen-ai-hub-sdk-js-backlog#96.
Fix type of CustomRequestConfig so it works with auto completion.
> chore: Adjust type of CustomRequestConfig

- packages/gen-ai-hub/src/orchestration/orchestration-client.ts
> fix: Do not use model for orchestration resolution

- packages/gen-ai-hub/src/client/openai/openai-types.ts
- packages/gen-ai-hub/src/index.ts
- packages/gen-ai-hub/src/utils/deployment-resolver.ts
AI/gen-ai-hub-sdk-js-backlog#99.
With this PR, we adapt which APIs are external / internal facing
> chore: Change API visibility

- packages/core/src/http-client.test.ts
- packages/core/src/http-client.ts
- test-util/mock-http.ts
Allows us to see the SDK in the cloud reporting dashboard.
> feat: Add Metering Header

- .changeset/silent-tools-beg.md
- .changeset/three-frogs-deliver.md
- .github/workflows/bump.yml
- .github/workflows/draft-release.yml
- .github/workflows/publish-canary.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
AI/gen-ai-hub-sdk-js-backlog#85.
Introduces scripts for bump, draft release and actual npm release.
Currently changelogs are ignored and removed (so changelog requires a manual step).
Current example draft release: https://github.com/SAP/ai-sdk-js/releases/tag/untagged-2984fb874f2023120360
> chore: Release

- .github/workflows/smoke-tests.yml
- tests/smoke-tests/test/smoke.test.ts
Multiple fixes:
* Fix URL
* Add missing slack notification
* Add missing shutdown after test
[successful run](https://github.com/SAP/ai-sdk-js/actions/runs/10793791417)
> fix: Smoke Test

- packages/core/src/http-client.ts
- packages/orchestration/src/orchestration-response.ts
- sample-code/src/orchestration.ts
- sample-code/src/server.ts
- tests/smoke-tests/test/smoke.test.ts
I found that the samples for orchestration do not show enough functionality and roughly implemented all features.
Error case could be improved, but maybe we do this after GA.
TODO:
> chore: Improve samples

- packages/orchestration/src/index.ts
- packages/orchestration/src/orchestration-client.test.ts
- packages/orchestration/src/orchestration-completion-post-request.test.ts
- packages/orchestration/src/orchestration-filter-utility.test.ts
- packages/orchestration/src/orchestration-filter-utility.ts
- sample-code/src/orchestration.ts
🚨 Style guide police in action ;)
> chore: Rename `azureContentFilter()` to `buildAzureContentFilter()`

- .changeset/ga-release.md
- .changeset/gen-ai-hub.md
- .changeset/kudos-to-the-great-team.md
- .changeset/sap-cloud-sdk-for-ai.md
We need changeset files (release notes) for the GA.
Here is the feature list from high level.
> chore: Add changesets

- packages/orchestration/src/index.ts
> chore: Remove grounding types from orchestration

- README.md
This PR should be merged just before the release.
> chore: Remove disclaimer before GA

- pnpm-lock.yaml
- tests/smoke-tests/package.json
I accidentally pushed the first missing dependency to main. This fixes the smoke tests.
> chore: Fix smoketests

- .changeset/kind-boxes-teach.md
- package.json
- packages/ai-api/package.json
- packages/core/package.json
- packages/foundation-models/package.json
- packages/langchain/package.json
- packages/langchain/src/openai/types.ts
- packages/orchestration/package.json
- pnpm-lock.yaml
- sample-code/package.json
- tests/e2e-tests/package.json
- tests/type-tests/package.json
I noticed that we had some unused dependencies, so I added a dependency check. Unfortunately this also showed that there were some missing (productive!!) dependencies.
> fix: Fix missing and unused dependencies

- .github/workflows/build.yml
~AI/gen-ai-hub-sdk-js-backlog#ISSUENUMBER.~
With this PR, we add our new dependency check also to our pipeline
> chore: Add dependency check to our pipeline

- CONTRIBUTING.md
AI/gen-ai-hub-sdk-js-backlog#140.
Reference GenAI contribution guidelines as requested by OSPO.
> docs: Reference GenAI contribution guidelines

- packages/foundation-models/README.md
- packages/orchestration/README.md
AI/gen-ai-hub-sdk-js-backlog#139.
> chore: Docs move custom request config

- CONTRIBUTING.md
- STYLEGUIDE.md
Linking the style guide for reference
> chore: Add style guide

- packages/foundation-models/src/azure-openai/client/inference/schema/azure-chat-extension-configuration.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/azure-chat-extension-type.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/azure-chat-extensions-message-context.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/azure-cosmos-db-chat-extension-configuration.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/azure-search-chat-extension-configuration.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/chat-completion-request-message-assistant.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/chat-completion-request-message-content-part-image.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/chat-completion-request-message-content-part-text.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/chat-completion-request-message-function.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/chat-completion-request-message-system.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/chat-completion-request-message-tool.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/chat-completion-request-message-user.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/create-chat-completion-request.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/on-your-data-api-key-authentication-options.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/on-your-data-connection-string-authentication-options.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/on-your-data-deployment-name-vectorization-source.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/on-your-data-endpoint-vectorization-source.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/on-your-data-system-assigned-managed-identity-authentication-options.ts
- packages/foundation-models/src/azure-openai/client/inference/schema/on-your-data-user-assigned-managed-identity-authentication-options.ts
After the discriminator fixes in the cloud SDK, the azure client is regenerated to reflect those changes
> chore: Re-generate azure client 

- pnpm-lock.yaml
- sample-code/src/server.ts
- tests/smoke-tests/package.json
- tests/smoke-tests/test/smoke.test.ts
AI/gen-ai-hub-sdk-js-backlog#153.
Our smoke tests are broken because their dependencies are incomplete.
With this PR they are updated, as well as some adjustments to the endpoints of our E2E tests.
> fix: Update dependencies of our smoke tests

- CONTRIBUTING.md
AI/gen-ai-hub-sdk-js-backlog#133.
Document how to release a new version.
> chore: Document release process

- .gitignore
AI/gen-ai-hub-sdk-js-backlog#ISSUENUMBER.
Please provide a description of what your change does and why it is needed.
> chore: Adjust git ignore for IDEA

- packages/orchestration/README.md
The previous [PR](https://github.com/SAP/ai-sdk-js/pull/225) was merged due to auto merge.
This is a follow up.
> chore: Improve Readme

- README.md
- packages/ai-api/README.md
- packages/core/README.md
- packages/foundation-models/README.md
- packages/langchain/README.md
- packages/orchestration/README.md
This PR applies following changes:
- Add product name (SAP Cloud SDK for AI) to every package, so the product name is reflected on npm side (doc and search results)
- Tell people, we are the official SDK 😄
> chore: Update Readme

- packages/ai-api/src/tests/deployment-api.test.ts
- packages/ai-api/src/utils/model.ts
Issue has been fixed a while ago, so removing the workaround should be safe.
> chore: Remove Backend_details workaround

- packages/orchestration/src/client/api/schema/filtering-module-config.ts
- packages/orchestration/src/client/api/schema/index.ts
- packages/orchestration/src/client/api/schema/template.ts
- packages/orchestration/src/client/api/schema/templating-module-config.ts
This PR introduces a new schema for template, which is not a breaking change.
> chore: Update schema for templates

- sample-code/src/langchain-azure-openai.ts
With this PR, we update the prompt used to test our RAG example code.
The new prompt specifically mentions that the model should showcase class instantiation, which hopefully results in stable tests.
> chore: Update RAG E2E test

- packages/foundation-models/README.md
AI/gen-ai-hub-sdk-js-backlog#175.
Add documentation for Azure OpenAI streaming in `foundation-models`.
> chore: Add documentation for Azure OpenAI streaming

- .github/PULL_REQUEST_TEMPLATE.md
Change: **SAP/ai-sdk-js-backlog**#ISSUENUMBER.
> fix: Change repo name in PR template

- .github/workflows/e2e-tests.yaml
- .github/workflows/fosstars.yml
- .github/workflows/smoke-tests.yml
Required after Dependabot updated the major version to 2.0.0
> fix: Slack Notification

- sample-code/README.md
- sample-code/src/foundation-models/azure-openai.ts
- sample-code/src/server.ts
- tests/e2e-tests/README.md
SAP/ai-sdk-js-backlog#185.
Added some documentation to describe the sample code. Separated e2e documentation from sample code.
> chore: Improve sample code documentation

- .github/PULL_REQUEST_TEMPLATE.md
* Outcome of retro discussion: https://sap-ml.slack.com/archives/C06TWGXQ8LC/p1734530645332459
* Remove DoD from (moved to BLI template, related change [here](https://github.com/SAP/ai-sdk-js-backlog/pull/198))
* Anything else that should be added? e.g. points from [here](https://github.tools.sap/AI/llm-orchestration/blob/main/docs/pull_request_template.md)?
> chore: Update PR template, remove DoD

- .changeset/fair-clocks-join.md
- packages/orchestration/README.md
- packages/orchestration/src/index.ts
- sample-code/README.md
- sample-code/src/index.ts
- sample-code/src/orchestration.ts
- sample-code/src/server.ts
- tests/e2e-tests/src/orchestration.test.ts
SAP/ai-sdk-js-backlog#193.
Sample code, e2e, documentation added for using image recognition in orchestration service. Types exported.
> feat: Support image recognition for orchestration

- .github/PULL_REQUEST_TEMPLATE.md
With this change, PRs will be properly linked to tickets in the backlog.
> chore: Add annotation to PR template for auto linking

- .changeset/big-mayflies-begin.md
> chore: Update big-mayflies-begin.md

- packages/ai-api/src/utils/deployment-resolver.ts
We got a user issue, as they saw the error message.
The root cause was because of the missing orchestration deployment.
With improved error message, I hope we can save time for debugging.
> chore: Improve error message for deployment resolver

- packages/ai-api/src/utils/deployment-resolver.ts
> chore: Fix typo

- packages/document-grounding/src/tests/vector-api.test.ts
- sample-code/src/document-grounding.ts
- sample-code/src/orchestration.ts
> chore: Use correct modelName and resource group in grounding e2e

- .changeset/release-notes.md
Add missing release notes:
Related to: https://github.com/SAP/ai-sdk-js/pull/514
> chore: Add release notes for prompt registry

- .changeset/lovely-cars-end.md
- packages/langchain/src/openai/util.test.ts
- packages/langchain/src/openai/util.ts
Closes https://github.com/SAP/ai-sdk-js/issues/528
> fix: Add tool_calls only if non-empty (Langchain)

- packages/document-grounding/package.json
- packages/langchain/package.json
- [document-grounding] improve the keyword section of package.json
- [langchain] use description from the readme like other packages
> chore: Improve keyword

- .changeset/release-notes-2.md
Add release notes for: https://github.com/SAP/ai-sdk-js/pull/523
> feat: Support configuring data masking for grounding inputs

- .github/workflows/dependabot-pnpm-lock.yml
> fix: Fix dependabot autofix action

- .github/workflows/bump.yml
- .github/workflows/draft-release.yml
Closes SAP/ai-sdk-js-backlog#237.
> chore: Create merged changelog

- .github/workflows/bump.yml
- .github/workflows/draft-release.yml
Add missing `@main` for `uses`.
> chore: Fix bump and draft release workflow

- pnpm-lock.yaml
- tests/smoke-tests/package.json
> chore: Fix smoke test due to missing dependency

- packages/langchain/src/orchestration/README.md
- packages/orchestration/README.md
Orchestration deployments are now available by default in the default RG -> removing the prerequisite
> chore: Improve Orchestration Documentation

- pnpm-lock.yaml
The lock file was broken due to dependabot PRs
> fix: PNPM lock file

- README.md
> fix: A typo

- packages/orchestration/src/orchestration-client.test.ts
- packages/orchestration/src/orchestration-client.ts
- test-util/data/orchestration/orchestration-chat-completion-yaml-template.yaml
Adds additional check for empty string and tests. Improve error handling
> chore: Add more checks and test

- .github/workflows/bump.yml
- .github/workflows/publish.yml
Uses the correct token for the release scripts
> fix: Release note script

- pnpm-lock.yaml
- tests/smoke-tests/package.json
Smoke test started failing with:
```
Cannot find package '@langchain/langgraph' imported from /home/vcap/app/dist/langchain-orchestration.js
```
> fix: Smoke test failure

- .changeset/happy-bobcats-wash.md
- packages/core/src/model-types.ts
- tests/type-tests/test/orchestration.test-d.ts
Closes SAP/ai-sdk-js-backlog#218.
> chore: Update available model list

- .changeset/dark-geese-laugh.md
- .changeset/mighty-lights-stay.md
> chore: Add changeset for the new orchestration spec and document grounding with SharePoint

- .changeset/itchy-ears-wink.md
> chore: Add changeset for template optional PR

- packages/langchain/src/orchestration/client.test.ts
- packages/langchain/src/orchestration/client.ts
Fix long running async operations on Timeout test
> fix: Timeout test with async operations LangChain streaming

- .changeset/little-zoos-float.md
Relates to SAP/ai-sdk-js-backlog#316.
> chore: Add changeset for LangChain Orchestration `bindTools()`

- .gitignore
> chore: Add .nvmrc to gitignore

- pnpm-lock.yaml
- sample-code/package.json
- sample-code/src/tutorials/mcp/mcp-adapter.ts
- sample-code/src/tutorials/mcp/weather-mcp-server.ts
- sample-code/src/tutorials/travel-itinerary-agent.ts
> chore: Add weather MCP in agent tutorial (#895)

- .changeset/clean-guests-drum.md
- .changeset/cold-women-start.md
- packages/core/src/model-types.ts
Closes SAP/ai-sdk-js-backlog#382.
Cherry pick commit to support `gpt-5` models.
> chore(v1): Update model list

- .changeset/clean-guests-drum.md
- packages/core/src/model-types.ts
Closes SAP/ai-sdk-js-backlog#382
- ~[ ] I've updated (v2-Upgrade-Guide.md)[./v2-Upgrade-Guide.md] in case my change has any implications for users updating to SDK v2~
Adds `gpt-5` models to the available model list.
> chore: Update model list

- .github/workflows/auto-fix-lint.yml
- .github/workflows/dependabot-pnpm-lock.yml
https://stackoverflow.com/a/69169858/18544589
Committing and pushing into a PR branch from an action won't trigger other actions if using GH token. We have to use PAT.
> chore: Use PAT again when committing to a PR which triggers other actions

- .github/workflows/pnpm-update.yml
> chore: Fix auto pnpm update pr title
